#!/usr/bin/env python

# Generate the list of ECF server domains (ecf.*.uscourts.gov)
# And dump their timezones to ecfzones.json

import collections
import json
import lxml.html
import re
import urllib2

from ecftimezone import ECFTimezone

PACERLINKS = 'http://www.pacer.gov/psco/cgi-bin/links.pl'

courts = set()

html = lxml.html.parse(urllib2.urlopen(PACERLINKS))
for e in html.iter('a'):
    link = e.get('href')
    if not link:
        continue
    match = re.match(r'^https?://ecf\.([^.]+)\.uscourts.gov', link)
    if match:
        courts.add(match.group(1))


f = open('ecfdomains.txt', 'w')
for c in sorted(courts):
    f.write(c + "\n")
f.close()

e = ECFTimezone()
d = {c: e.timezone(c) for c in courts}
od = collections.OrderedDict(sorted(d.items()))

# Unfortunately pprint dumps dictionaries with then open { on the ame
# line as the first line of the dictionary. Go with JSON instead.

jsonform = json.dumps(od, indent=4, separators=(',', ': '))

f = open('ecfzones.json', 'w')
f.write(jsonform)
f.close()

# Or in python form:

f = open('ecfzones.py', 'w')
f.write(r'''#!/usr/bin/env python
# Generated by generate.py


class ECFTimezones:

    COURT = %s
''' % (jsonform.replace("\n", "\n    ")))
f.close()
